languageCode = "id"
languageName = "Indonesian"
weight = 1
title = "Tamago"

[params]
  displayName = "ID"
  isoCode = "id"
  rtl = false
  dateFormat = "2 January 2006"
   logo = "img/logo.png"
   secondaryLogo = "img/logo.png"
   description = "Bukan Blogger tapi ngeblog, bukan penulis tapi menulis, bukan programmer tapi mainannya coding"
   copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "Tamago!"
   image = "img/logo-profile.png"
   headline = "Jika mencintaimu itu hanyalah mimpi, maka biarkanlah aku bermimpi selamanya"
   bio = "Kamu itu seperti langit yang tidak pernah bisa aku gapai"
   links = [
     { email = "mailto:tamagotchi465@gmail.com" },
#     { link = "https://adhiwijaya.id/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/weebers.weebstersrapperdjogja" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { github = "https://github.com/petanimicin" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
     { instagram = "https://instagram.com/tamagoid_" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
     { twitter = "https://twitter.com/tamago_id_" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
   ]
